SmartGridready/SGrJava

- InterfaceFactory/CommHandler4Modbus/src/test/java/communicator/modbus/integrationtest/SGrTestCommunicator.java
- InterfaceFactory/CommHandler4Modbus/src/test/resources/SGr_04_0014_0000_WAGO_Testsystem_V1.0.xml
Improvement of the SGrTestCommunicator usability.
> 33 add bitmap and enum handling to the SGrTestCommunicator

- InterfaceFactory/CommHandler4Modbus/src/main/java/communicator/common/impl/SGrDeviceBase.java
- InterfaceFactory/CommHandler4Modbus/src/test/java/communicator/modbus/impl/SetGetValConversionTest.java
- InterfaceFactory/CommHandler4Modbus/src/test/resources/devicedescriptions.yaml
Fixed renaming of DataDirection to DataDirectionProduct.
Fixed filenames used for DeviceLoaderTest.
> Fixed renaming of DataDirection to DataDirectionProduct.

- InterfaceFactory/CommHandler4Modbus/src/main/java/communicator/common/api/SGrDeviceBuilder.java
- InterfaceFactory/CommHandler4Modbus/src/main/java/communicator/common/helper/XmlResourceLoader.java
- InterfaceFactory/CommHandler4Modbus/src/test/java/communicator/common/api/SGrDeviceBuilderTest.java
- InterfaceFactory/CommHandler4Modbus/src/test/resources/SGr_04_0014_0000_WAGO_SmartMeterV0.2.1-Arrays.xml
- InterfaceFactory/CommHandler4Modbus/src/test/resources/SGr_04_0014_0000_WAGO_SmartMeterV0.2.1-Blocktransfer.xml
- InterfaceFactory/CommHandler4Modbus/src/test/resources/SGr_04_0014_0000_WAGO_SmartMeterV0.2.1-GenericAttributes.xml
Fixed XmlResourceLoader and DeviceDescriptionLoader by using resource name 'eid.xml'.
> Added unit-tests for SGrDeviceBuilder.

- InterfaceFactory/CommHandler4Modbus/src/main/java/communicator/common/api/dto/DataPoint.java
- InterfaceFactory/CommHandler4Modbus/src/main/java/communicator/common/api/dto/DataType.java
- InterfaceFactory/CommHandler4Modbus/src/main/java/communicator/common/impl/SGrDeviceBase.java
- InterfaceFactory/CommHandler4Modbus/src/main/java/utils/SGrGDPTypeToNameMapper.java
- InterfaceFactory/CommHandler4Modbus/src/test/java/communicator/common/impl/SGrDeviceBaseTest.java
- InterfaceFactory/CommHandler4Modbus/src/test/resources/SGr_04_0014_0000_WAGO_Testsystem_V1.0.xml
- Reports valid data-type ranges for numeric values
- Reports valid values for enums and bitmaps
> Added data-point's data-type details to the introspective reading.

- InterfaceFactory/CommHandler4Modbus/build.gradle
- build.gradle
The version will be created from the latest tag and add '-SNAPSHOT' if:
- the current branch during build is not master
- the current branch is not clean (some uncommited source changes)
- the branch has some commits after the tag
> Added palantir to support git-tag based versioning.

- CommHandler/src/main/java/com/smartgridready/communicator/messaging/client/HiveMqtt5MessagingClient.java
> HiveMqtt5MessagingClient: Fixed wrong parameter name timeoutSec -> timeoutMs.

- CommHandler/src/test/java/com/smartgridready/communicator/modbus/impl/IBTlabLoopTester.java
- CommHandler/src/test/java/com/smartgridready/communicator/modbus/impl/IOPdemoBOX.java
- CommHandler/src/test/resources/devicedescriptions.yaml
- SGrSpecification/.classpath
renamed required EID according to specification
> fixed tests after renaming ABB B23 EID in specification's main branch.

- CommHandler/build.gradle
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/client/HiveMqtt5MessagingClient.java
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/client/HiveMqtt5MessagingClientFactory.java
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/impl/SGrMessagingDevice.java
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/mapper/BrokerListMapper.java
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/mapper/MessageBrokerMapper.java
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/mapper/MessageFilterMapper.java
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/mapper/MessagingInterfaceDescMapper.java
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/mapper/PlatformTypeMapper.java
- CommHandler/src/main/java/com/smartgridready/communicator/modbus/helper/ModbusUtil.java
- CommHandler/src/main/java/com/smartgridready/communicator/modbus/impl/GenDriverAPI4ModbusRTUWrapper.java
- CommHandler/src/main/java/com/smartgridready/communicator/modbus/impl/SGrModbusGatewayFactory.java
- CommHandler/src/test/java/com/smartgridready/communicator/messaging/client/Mqtt5MessagingClientTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/messaging/mapper/MessagingInterfaceDescMapperTest.java
- CommHandler/src/test/resources/devicedescriptions.yaml
- build.gradle
Adaption to new SGrDriverApi messaging interface that is independent of sgr-specification package (generated classes)
> 76 refactoring and removal of legacy functionality

- CommHandler/src/main/java/com/smartgridready/communicator/common/helper/XmlResourceLoader.java
Does now log exact location of the parse error within the EI-XML.
> Improved DeviceDescriptionLoader to report SAXParsing errors.

- CommHandler/build.gradle
- Specification/gradle.properties
Commhandler and specification have been released, now using those release dependencies.
> set dependencies to release.

- CommHandler/CHANGELOG.md
- Specification/CHANGELOG.md
added a changelog based on the current state of the library.
> added changelog files.

- GenDriverAPI/CHANGELOG.md
- GenDriverAPI/build.gradle
- GenDriverAPI/gradle.properties
final merge of GenDriverAPI code
> migrated driver API code from master branch.

- .github/workflows/driver-api-ci.yaml
- CommHandler/CHANGELOG.md
- fixed CI build
- updated changelog after bugfix release 2.0.1
> fixed CI build of sgr-driver-api.

- CommHandler/src/main/java/com/smartgridready/communicator/common/api/GenDeviceApi.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/dto/DataPoint.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/dto/DeviceInfo.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/dto/FunctionalProfile.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/impl/SGrDeviceBase.java
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/api/GenDeviceApi4Messaging.java
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/impl/SGrMessagingDevice.java
- CommHandler/src/main/java/com/smartgridready/communicator/modbus/impl/SGrModbusDevice.java
- CommHandler/src/main/java/com/smartgridready/communicator/rest/impl/SGrRestApiDevice.java
- CommHandler/src/test/java/com/smartgridready/communicator/async/AsyncClemapWagoTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/common/impl/SGrDeviceBaseTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/messaging/impl/SGrMessagingDeviceTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/rest/impl/ClemapRestApiTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/rest/impl/SGrRestAPIDeviceTest.java
expanded the generic API, so that basically all essential methods can be called from there.
> 104 add interfaces to be in sync with python

- CommHandler/src/main/java/com/smartgridready/communicator/modbus/impl/SGrModbusDevice.java
- CommHandler/src/main/java/com/smartgridready/communicator/rest/http/client/ApacheHttpRequest.java
- CommHandler/src/test/java/com/smartgridready/communicator/common/api/SGrDeviceBuilderTest.java
This changes provide more detailed error information for modbus and REST-API devices. 
This facilitates error analyis on CommHandler clients like sgr-intermediary etc..
> Improved error handling on SGrModbusDevice and ApacheHttpRequest.

- CommHandler/CHANGELOG.md
- GenDriverAPI/CHANGELOG.md
- GenDriverAPI/gradle.properties
just the updated changelogs after creating the releases.
> After release 2.1.0

- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/DataType.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/EnumRecord.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/EnumValue.java
- CommHandler/src/test/java/com/smartgridready/communicator/common/api/EnumValueTest.java
fixes a bug where device cannot be loaded due to missing ordinals.
> fixed handling of undefined ENUM literals and ordinals

- CommHandler/CHANGELOG.md
- CommHandler/gradle.properties
ENUM bugfix needs to be included ASAP
> prepare for commhandler release 2.1.1.

- CommHandler/src/test/resources/devicedescriptions.yaml
Fixes failing tests due to changes in EIDs in master branch of SGrSpecifications.
> Fix test devicedescription

- CommHandler/src/main/java/com/smartgridready/communicator/common/impl/SGrDeviceBase.java
- CommHandler/src/main/java/com/smartgridready/communicator/messaging/impl/SGrMessagingDevice.java
- CommHandler/src/main/java/com/smartgridready/communicator/modbus/impl/SGrModbusDevice.java
- CommHandler/src/main/java/com/smartgridready/communicator/rest/impl/SGrRestApiDevice.java
moved code for unit conversion to device base. added unit conversion to messaging device.
> Added unit conversion to messaging device

- CommHandler/build.gradle
- CommHandler/gradle.properties
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/ArrayValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/BitmapValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/DateTimeValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/EnumValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/Int64UValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/NumberValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/StringValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/Value.java
- CommHandler/src/test/java/com/smartgridready/communicator/common/api/DateTimeValueTest.java
Added implementation of DateTime type.
Supports ISO-8601 strings and 64bit timestamps (UNIX / Java).
This PR is a preparation to integrate JSON data type.
> support datetime data type

- CommHandler/CHANGELOG.md
- CommHandler/build.gradle
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/ArrayValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/BitmapValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/BooleanValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/DataType.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/DateTimeValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/EnumValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/Int64UValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/JsonValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/NumberValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/StringValue.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/Value.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/helper/JsonHelper.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/helper/JsonWriter.java
- CommHandler/src/main/java/com/smartgridready/communicator/rest/http/client/RestServiceClient.java
- CommHandler/src/test/java/com/smartgridready/communicator/common/api/JsonValueTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/common/api/StringValueTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/common/helper/JsonReaderWriterTest.java
implemented JSON data type with JsonNode as generic type.
extended with method to convert JSON to Java object.
optimized internal processing of JSON data, use JsonNode wherever possible.
When this PR is OK and merged, a new commhandler release 2.3.0 can be created.
> handle json data type

- CommHandler/CHANGELOG.md
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/dto/FunctionalProfile.java
- CommHandler/src/main/java/com/smartgridready/communicator/common/api/values/JsonValue.java
- CommHandler/src/test/java/com/smartgridready/communicator/common/api/JsonValueTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/common/helper/JsonMapperTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/messaging/impl/SGrMessagingDeviceTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/rest/impl/TariffProvidersTest.java
- CommHandler/src/test/resources/SGr_04_0015_xxxx_StiebelEltron_HeatPump_V1.0.0.xml
- CommHandler/src/test/resources/SGr_05_mmmm_dddd_Dynamic_Tariffs_GroupeE_V1.0.xml
- CommHandler/src/test/resources/SGr_05_mmmm_dddd_Dynamic_Tariffs_Swisspower_V1.0.xml
- CommHandler/src/test/resources/SGr_XX_HiveMQ_MQTT_Cloud.xml
- CommHandler/src/test/resources/devicedescriptions.yaml
only include readable data points when getting all data point values from FP.
fixed conversion of JSON value.
> fixed get all values from FP and JSON conversion

- CommHandler/CHANGELOG.md
- CommHandler/build.gradle
- CommHandler/gradle.properties
updated driver API, Apache driver and include JSON bugfixes.
> prepare commhandler release 2.4.1

- CommHandler/src/test/java/com/smartgridready/communicator/async/AsyncClemapWagoTest.java
- CommHandler/src/test/java/com/smartgridready/communicator/modbus/impl/IntrospectiveDeviceTester.java
- CommHandler/src/test/java/com/smartgridready/communicator/rest/impl/ClemapRestApiTest.java
- CommHandler/src/test/resources/devicedescriptions.yaml
fixed missing EIDs referenced in tests, after renaming in specification repo.
> fixed missing test EIDs
